routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard2', 'DashboardController@index')->name('dashboard2');

Route::group(['middleware' => ['auth']], function () {

    /**
     * Master Role
     */
    Route::prefix('master-roles')->namespace('MasterRole')->name('master-role.')->group(function () {
        // Permission
        Route::resource('permission', 'PermissionController');
        Route::post('permission/api', 'PermissionController@api')->name('permission.api');
        // Role
        Route::resource('role', 'RoleController');
        Route::prefix('role')->name('role.')->group(function () {
            Route::post('api', 'RoleController@api')->name('api');
            Route::get('{id}/addPermissions', 'RoleController@permission')->name('addPermissions');
            Route::post('storePermissions', 'RoleController@storePermission')->name('storePermissions');
            Route::get('{id}/getPermissions', 'RoleController@getPermissions')->name('getPermissions');
            Route::delete('{name}/destroyPermission', 'RoleController@destroyPermission')->name('destroyPermission');
        });
        // Pengguna
        Route::resource('pengguna', 'PenggunaController');
        Route::prefix('pengguna')->name('pengguna.')->group(function () {
            Route::post('api', 'PenggunaController@api')->name('api');
            Route::get('kabupatenByProvinsi/{id}', 'PenggunaController@kabupatenByProvinsi')->name('kabupatenByProvinsi');
            Route::get('kecamatanByKabupaten/{id}', 'PenggunaController@kecamatanByKabupaten')->name('kecamatanByKabupaten');
            Route::get('kelurahanByKecamatan/{id}', 'PenggunaController@kelurahanByKecamatan')->name('kelurahanByKecamatan');
            Route::get('editPassword/{id}', 'PenggunaController@editPassword')->name('editPassword');
            Route::post('updatePassword/{id}', 'PenggunaController@updatePassword')->name('updatePassword');
        });
    });

    /**
     * Master Pemilik
     */
    Route::prefix('master-pemiliks')->namespace('MasterPemilik')->name('master-pemilik.')->group(function () {
        // Pemilik
        Route::resource('pemilik', 'PemilikController');
        Route::post('pemilik/api', 'PemilikController@api')->name('pemilik.api');
        // Pemilik Ketentuan
        Route::resource('pemilikKetentuan', 'PemilikKetentuanController');
        Route::post('pemilikKetentuan/api', 'PemilikKetentuanController@api')->name('pemilikKetentuan.api');
    });

    /**
     * Master Config
     */
    Route::prefix('master-configs')->namespace('MasterConfig')->name('master-config.')->group(function () {
        // App
        Route::resource('app', 'AppController');
        Route::post('app/api', 'AppController@api')->name('app.api');
        // Home
        Route::resource('home', 'CHomeController');
        Route::post('home/api', 'CHomeController@api')->name('home.api');
        // Auth
        Route::resource('auth', 'AuthController');
        Route::post('auth/api', 'AuthController@api')->name('auth.api');
        // Theme
        Route::resource('theme', 'ThemeController');
        Route::post('theme/api', 'ThemeController@api')->name('theme.api');
        // Splash
        Route::resource('splash', 'SplashController');
        Route::post('splash/api', 'SplashController@api')->name('splash.api');
    });

    /**
     * Master Merchant
     */
    Route::prefix('master-merchants')->namespace('MasterMerchant')->name('master-merchant.')->group(function () {
        // Merchant
        Route::resource('merchant', 'MerchantController');
        Route::post('merchant/api', 'MerchantController@api')->name('merchant.api');
        // Jenis Merchant
        Route::resource('jenisMerchant', 'JenisMerchantController');
        Route::post('jenisMerchant/api', 'JenisMerchantController@api')->name('jenisMerchant.api');
    });

    /**
     * Master Payment
     */
    Route::prefix('master-payments')->namespace('MasterPayment')->name('master-payment.')->group(function () {
        // Payment
        Route::resource('payment', 'PaymentController');
        Route::post('payment/api', 'PaymentController@api')->name('payment.api');
        // Sub Payment
        Route::resource('subPayment', 'SubPaymentController');
        Route::post('subPayment/api', 'SubPaymentController@api')->name('subPayment.api');
        // Sub Detail Payment
        Route::resource('subDetailPayment', 'SubDetailPaymentController');
        Route::post('subDetailPayment/api', 'SubDetailPaymentController@api')->name('subDetailPayment.api');
        Route::get('subDetailPayment/subPaymentByPayment/{id}', 'SubDetailPaymentController@subPaymentByPayment')->name('subDetailPayment.subPaymentByPayment');
    });

    /**
     * Page Not Found
     */
    Route::get('blank-page', 'BlankPageController@index')->name('blank-page');

    /**
     * Master Media
     */
    Route::prefix('master-media')->namespace('MasterMedia')->name('master-media.')->group(function () {
        // Iklan
        Route::resource('iklan', 'IklanController');
        Route::post('iklan/api', 'IklanController@api')->name('iklan.api');
        // Berita
        Route::resource('berita', 'BeritaController');
        Route::post('berita/api', 'BeritaController@api')->name('berita.api');
    });

    /**
     * Master User
     */
    Route::prefix('master-user')->namespace('MasterUser')->name('master-user.')->group(function () {
        // User
        Route::resource('user', 'UserController');
        Route::post('user/api', 'UserController@api')->name('user.api');
    });

    /**
     * Master Transaksi
     */
    Route::prefix('master-transaksi')->namespace('MasterTransaksi')->name('master-transaksi.')->group(function () {
        // Transaksi
        Route::resource('transaksi', 'TransaksiController');
        Route::post('transaksi/api', 'TransaksiController@api')->name('transaksi.api');
    });

    Route::prefix('logviewer')->namespace('LogViewer')->name('logviewer.')->group(function () {
        Route::resource('logs', 'LogsController');
    });
});

app/Http/Controllers/MasterRole/PenggunaController.php
<?php

namespace App\Http\Controllers\MasterRole;

use Auth;
use DataTables;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

// Models
use App\User;
use App\Models\Provinsi;
use App\Models\Kabupaten;
use App\Models\Kecamatan;
use App\Models\Kelurahan;
use App\Models\TmPemilik;
use App\Models\AdminDetails;
use App\Models\ModelHasRoles;
use Spatie\Permission\Models\Role;

class PenggunaController extends Controller
{
    protected $route = 'master-role.pengguna.';
    protected $view  = 'pages.masterRoles.pengguna.';
    protected $title = 'Config pengguna';
    protected $path  = 'profile/admin/';

    public function index()
    {
        $route = $this->route;
        $title = $this->title;

        $roles    = Role::select('id', 'name')->get();
        $provinsi = Provinsi::select('id', 'kode', 'n_provinsi')->get();
        $pemilik  = TmPemilik::select('id', 'nama')->get();

        return view($this->view . 'index', compact(
            'route',
            'title',
            'roles',
            'provinsi',
            'pemilik'
        ));
    }

    public function api()
    {
        $pengguna = AdminDetails::whereNotIn('admin_id', [Auth::user()->id])->get();

        return DataTables::of($pengguna)
            ->addColumn('action', function ($p) {
                return "
                <a href='#' onclick='remove(" . $p->id . ")' class='text-danger' title='Hapus Permission'><i class='icon-remove'></i></a>";
            })
            ->editColumn('admin_id', function ($p) {
                return "<a href='" . route($this->route . 'show', $p->id) . "' class='text-primary' title='Show Data'>" . $p->admin->username . "</a>";
            })
            ->editColumn('tmpemilik_id', function ($p) {
                return $p->admin->tmpemilik->nama;
            })
            ->editColumn('foto',  function ($p) {
                if ($p->foto != null) {
                    return "<img width='50' height='50' class='img-circular rounded-circle mx-auto d-block' alt='photo' src='" . config('app.sftp_src') . "/profile/admin/" . $p->foto . "'>";
                } else {
                    return "<img width='50' height='50' class='img-circular rounded-circle mx-auto d-block' alt='photo' src='" . asset('images/boy.png') . "'>";
                }
            })
            ->addIndexColumn()
            ->rawColumns(['action', 'foto', 'admin_id', 'tmpemilik_id'])
            ->toJson();
    }

    public function kabupatenByProvinsi($provinsi_id)
    {
        return Kabupaten::select('id', 'n_kabupaten')->where('provinsi_id', $provinsi_id)->get();
    }

    public function kecamatanByKabupaten($kabupaten_id)
    {
        return Kecamatan::select('id', 'n_kecamatan')->where('kabupaten_id', $kabupaten_id)->get();
    }

    public function kelurahanByKecamatan($kecamatan_id)
    {
        return Kelurahan::select('id', 'n_kelurahan')->where('kecamatan_id', $kecamatan_id)->get();
    }

    public function store(Request $request)
    {
        $request->validate([
            'username' => 'required|unique:admins',
            'password' => 'required',
            'role_id'  => 'required',
            'nik'      => 'required|min:16',
            'n_admin'  => 'required',
            'email'    => 'required|email|unique:admin_details',
            'telpn'    => 'required|unique:admin_details|max:12',
            'alamat'   => 'required',
            't_lahir'  => 'required',
            'd_lahir'  => 'required',
            'jenis_kelamin' => 'required',
            'pekerjaan'     => 'required',
            'kelurahan_id'  => 'required',
            'foto'          => 'required|mimes:png,jpg,jpeg|max:2024',
            'tmpemilik_id'  => 'required'
        ]);

        /** Tahapan :
         * 1. admins
         * 2. admins_details
         * 3. model_has_roles
         */

        //  Tahap 1
        $username = $request->username;
        $password = $request->password;
        $tmpemilik_id = $request->tmpemilik_id;

        $admin = new User();
        $admin->username = $username;
        $admin->password = Hash::make($password);
        $admin->tmpemilik_id = $tmpemilik_id;
        $admin->save();

        // Tahap 2
        $get_admin_id = User::select('id')->latest()->first();
        $nik     = $request->nik;
        $n_admin = $request->n_admin;
        $email   = $request->email;
        $telpn   = $request->telpn;
        $alamat  = $request->alamat;
        $t_lahir = $request->t_lahir;
        $d_lahir = $request->d_lahir;
        $jenis_kelamin = $request->jenis_kelamin;
        $pekerjaan     = $request->pekerjaan;
        $kelurahan_id  = $request->kelurahan_id;

        $file     = $request->file('foto');
        $fileName = time() . "." . $file->getClientOriginalName();
        $request->file('foto')->storeAs($this->path, $fileName, 'sftp', 'public');

        $admin_detail = new AdminDetails();
        $admin_detail->admin_id = $get_admin_id->id;
        $admin_detail->nik      = $nik;
        $admin_detail->n_admin  = $n_admin;
        $admin_detail->email    = $email;
        $admin_detail->telpn    = $telpn;
        $admin_detail->alamat   = $alamat;
        $admin_detail->t_lahir  = $t_lahir;
        $admin_detail->d_lahir  = $d_lahir;
        $admin_detail->foto     = $fileName;
        $admin_detail->jenis_kelamin = $jenis_kelamin;
        $admin_detail->pekerjaan     = $pekerjaan;
        $admin_detail->kelurahan_id  = $kelurahan_id;
        $admin_detail->save();

        // Tahap 3
        $path    = 'app\User';
        $role_id = $request->role_id;

        $model_has_role = new ModelHasRoles();
        $model_has_role->role_id    = $role_id;
        $model_has_role->model_type = $path;
        $model_has_role->model_id   = $get_admin_id->id;
        $model_has_role->save();

        return response()->json([
            'message' => 'Data ' . $this->title . ' berhasil tersimpan.'
        ]);
    }

    public function show($id)
    {
        $route = $this->route;
        $title = $this->title;

        $admin_detail = AdminDetails::findOrFail($id);
        $admin    = User::whereid($admin_detail->admin_id)->first();
        $roles    = Role::select('id', 'name')->get();
        $provinsi = Provinsi::select('id', 'kode', 'n_provinsi')->get();
        $pemilik  = TmPemilik::select('id', 'nama')->get();

        // get role_id by user
        $model_has_role = ModelHasRoles::where('model_id', $admin_detail->admin_id)->first();
        $role  = Role::select('id', 'name')->whereid($model_has_role->role_id)->first();

        return view($this->view . 'show', compact(
            'route',
            'title',
            'admin_detail',
            'admin',
            'roles',
            'role',
            'provinsi',
            'pemilik'
        ));
    }

    public function update(Request $request, $id)
    {
        $admin_detail = AdminDetails::find($id);
        $request->validate([
            'username' => 'required|unique:admins,username,' . $admin_detail->admin_id,
            'role_id'  => 'required',
            'nik'      => 'required|min:16',
            'n_admin'  => 'required',
            'email'    => 'required|email|unique:admin_details,email,' . $id,
            'telpn'    => 'required|unique:admin_details,telpn,' . $id,
            'alamat'   => 'required',
            't_lahir'  => 'required',
            'd_lahir'  => 'required',
            'jenis_kelamin' => 'required',
            'pekerjaan'     => 'required',
            'tmpemilik_id'  => 'required'
        ]);

        /** Tahapan :
         * 1. admins
         * 2. admins_details
         * 3. model_has_roles
         */

        //  Tahap 1
        $username     = $request->username;
        $tmpemilik_id = $request->tmpemilik_id;
        $admin        = User::find($admin_detail->admin_id);
        $admin->update([
            'username'     => $username,
            'tmpemilik_id' => $tmpemilik_id
        ]);

        // Tahap 2
        $nik     = $request->nik;
        $n_admin = $request->n_admin;
        $email   = $request->email;
        $telpn   = $request->telpn;
        $alamat  = $request->alamat;
        $t_lahir = $request->t_lahir;
        $d_lahir = $request->d_lahir;
        $jenis_kelamin = $request->jenis_kelamin;
        $pekerjaan     = $request->pekerjaan;

        if ($request->foto != null) {
            $request->validate([
                'foto' => 'required|mimes:png,jpg,jpeg|max:2024'
            ]);

            $file = $request->file('foto');
            $fileName = time() . "." . $file->getClientOriginalName();
            $request->file('foto')->storeAs($this->path, $fileName, 'sftp', 'public');

            // delete from storage
            $exist = $admin_detail->foto;
            Storage::disk('sftp')->delete($this->path . $exist);

            $admin_detail->update([
                'nik'     => $nik,
                'n_admin' => $n_admin,
                'email'   => $email,
                'telpn'   => $telpn,
                'alamat'  => $alamat,
                't_lahir' => $t_lahir,
                'd_lahir' => $d_lahir,
                'jenis_kelamin' => $jenis_kelamin,
                'pekerjaa n'    => $pekerjaan,
                'foto'          => $fileName
            ]);
        } else {
            $admin_detail->update([
                'nik'     => $nik,
                'n_admin' => $n_admin,
                'email'   => $email,
                'telpn'   => $telpn,
                'alamat'  => $alamat,
                't_lahir' => $t_lahir,
                'd_lahir' => $d_lahir,
                'jenis_kelamin' => $jenis_kelamin,
                'pekerjaan'     => $pekerjaan,
            ]);
        }

        // Tahap 3
        $role_id = $request->role_id;

        $model_has_role = ModelHasRoles::wheremodel_id($admin_detail->admin_id);

resources/views/pages/masterRoles/permission/index.blade.php
@extends('layouts.app')
@section('title', '| Data Permission')
@section('content')
<div class="page has-sidebar-left height-full">
    <header class="blue accent-3 relative nav-sticky">
        <div class="container-fluid text-white">
            <div class="row p-t-b-10 ">
                <div class="col">
                    <h4>
                        <i class="icon icon-clipboard-list2"></i>
                        Data {{ $title }}
                    </h4>
                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid my-3">
        <div class="row">
            <div class="col-md-8">
                <div class="card no-b">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="dataTable" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <th width="30">No</th>
                                    <th>Nama</th>
                                    <th width="80">Guard Name</th>
                                    <th width="60"></th>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div id="alert"></div>
                <div class="card no-b">
                    <div class="card-body">
                        <form class="needs-validation" id="form" method="POST"  enctype="multipart/form-data" novalidate>
                            {{ method_field('POST') }}
                            <input type="hidden" id="id" name="id"/>
                            <h4 id="formTitle">Tambah Data</h4><hr>
                            <div class="form-row form-inline">
                                <div class="col-md-12">
                                    <div class="form-group m-0">
                                        <label for="name" class="col-form-label s-12 col-md-4">Nama</label>
                                        <input type="text" name="name" id="name" placeholder="" class="form-control r-0 light s-12 col-md-8" autocomplete="off" required/>
                                    </div>
                                    <div class="form-group m-0">
                                        <label for="guard_name" class="col-form-label s-12 col-md-4">Guard Name</label>
                                        <input type="text" name="guard_name" id="guard_name" placeholder="" class="form-control r-0 light s-12 col-md-8" autocomplete="off" required/>
                                    </div>
                                    <div class="mt-2" style="margin-left: 34%">
                                        <button type="submit" class="btn btn-primary btn-sm" id="action"><i class="icon-save mr-2"></i>Simpan<span id="txtAction"></span></button>
                                        <a class="btn btn-sm" onclick="add()" id="reset">Reset</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script type="text/javascript">
    var table = $('#dataTable').dataTable({
        processing: true,
        serverSide: true,
        order: [ 0, 'asc' ],
        ajax: {
            url: "{{ route('master-role.permission.api') }}",
            method: 'POST'
        },
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false, align: 'center', className: 'text-center'},
            {data: 'name', name: 'name'},
            {data: 'guard_name', name: 'guard_name'},
            {data: 'action', name: 'action', orderable: false, searchable: false, className: 'text-center'}
        ]
    });

    function add(){
        save_method = "add";
        $('#form').trigger('reset');
        $('#formTitle').html('Tambah Data');
        $('input[name=_method]').val('POST');
        $('#txtAction').html('');
        $('#reset').show();
        $('#name').focus();
    }

    add();
    $('#form').on('submit', function (e) {
        if ($(this)[0].checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
        }
        else{
            $('#alert').html('');
            $('#action').attr('disabled', true);
            url = (save_method == 'add') ? "{{ route('master-role.permission.store') }}" : "{{ route('master-role.permission.update', ':id') }}".replace(':id', $('#id').val());
            $.post(url, $(this).serialize(), function(data){
                $('#alert').html("<div role='alert' class='alert alert-success alert-dismissible'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>×</span></button><strong>Success!</strong> " + data.message + "</div>");
                table.api().ajax.reload();
                if(save_method == 'add') add();
            }, "JSON").fail(function(data){
                err = ''; respon = data.responseJSON;
                $.each(respon.errors, function(index, value){
                    err += "<li>" + value +"</li>";
                });
                $('#alert').html("<div role='alert' class='alert alert-danger alert-dismissible'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>×</span></button><strong>Error!</strong> " + respon.message + "<ol class='pl-3 m-0'>" + err + "</ol></div>");
            }).always(function(){
                $('#action').removeAttr('disabled');
            });
            return false;
        }
        $(this).addClass('was-validated');
    });

    function edit(id) {
        save_method = 'edit';
        var id = id;
        $('#alert').html('');
        $('#form').trigger('reset');
        $('#formTitle').html("Edit Data <a href='#' onclick='add()' class='btn btn-outline-danger btn-xs pull-right ml-2'>Batal</a>");
        $('#txtAction').html(" Perubahan");
        $('#reset').hide();
        $('input[name=_method]').val('PATCH');
        $.get("{{ route('master-role.permission.edit', ':id') }}".replace(':id', id), function(data){
            $('#id').val(data.id);
            $('#name').val(data.name).focus();
            $('#guard_name').val(data.guard_name);
        }, "JSON").fail(function(){
            reload();
        });
    }

    function remove(id){
        $.confirm({
            title: '',
            content: 'Apakah Anda yakin akan menghapus data ini ?',
            icon: 'icon icon-question amber-text',
            theme: 'modern',
            closeIcon: true,
            animation: 'scale',
            type: 'red',
            buttons: {
                ok: {
                    text: "ok!",
                    btnClass: 'btn-primary',
                    keys: ['enter'],
                    action: function(){
                        $.post("{{ route('master-role.permission.destroy', ':id') }}".replace(':id', id), {'_method' : 'DELETE'}, function(data) {
                           table.api().ajax.reload();
                            if(id == $('#id').val()) add();
                        }, "JSON").fail(function(){
                            reload();
                        });
                    }
                },
                cancel: function(){}
            }
        });
    }

</script>
@endsection